const iconMap = {
  "icon-1": { icon: "🏃" },
  "icon-2": { icon: "🚶" },
  "icon-3": { icon: "🚴" },
  "icon-4": { icon: "🏊" },
  "icon-5": { icon: "⚽" },
  "icon-6": { icon: "🏀" },
  "icon-7": { icon: "🎯" },
  "icon-8": { icon: "🎮" },
  "icon-9": { icon: "🎧" },
  "icon-10": { icon: "📚" },
  "icon-11": { icon: "🧠" },
  "icon-12": { icon: "💡" },
  "icon-13": { icon: "✏️" },
  "icon-14": { icon: "📝" },
  "icon-15": { icon: "💻" },
  "icon-16": { icon: "🖥️" },
  "icon-17": { icon: "📱" },
  "icon-18": { icon: "⌛" },
  "icon-19": { icon: "⏰" },
  "icon-20": { icon: "📅" },
  "icon-21": { icon: "🔥" },
  "icon-22": { icon: "⭐" },
  "icon-23": { icon: "🛌🏼" },
  "icon-24": { icon: "💪🏻" },
  "icon-25": { icon: "🌙" },
  "icon-26": { icon: "☀️" },
  "icon-27": { icon: "📵" },
  "icon-28": { icon: "🌳" },
  "icon-29": { icon: "🍎" },
  "icon-30": { icon: "💧" },
};

export default iconMap;
